apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil42-deployment
  labels:
    app: wil42
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil42
  template:
    metadata:
      labels:
        app: wil42
    spec:
      containers:
      - name: wil42
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: wil42-service
spec:
  selector:
    app.kubernetes.io/name: wil42
  type: NodePort
  ports:
    - protocol: TCP
      port: 8042
      targetPort: 8888
      nodePort: 30000